version: '3'
services:
  dev:
    image: lambdawg/wg5
    container_name: ld-dev-hot
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - image-volume:/app/assets/images
    command: npm run dev:hot
volumes:
  node_modules:
  dev-db-volume:
  image-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /src/assets/images